import FuegoIPClipper from './images/clipper.png'
import img1 from './images/image-product-1.jpg'
import img2 from './images/image-product-2.jpg'
import img3 from './images/image-product-3.jpg'
import img4 from './images/image-product-4.jpg'
import MiniSoplete from './images/products-images/soplete_pequeño.jpg'
import MiniSopleteNegro from './images/products-images/soplete_pequeño_negro2.jpg'
import MiniSopleteNaranja from './images/products-images/soplete_pequeño_naranja.jpg'
import MiniSopleteVerde from './images/products-images/soplete_pequeño_verde.jpg'

const data2 = {
  allProducts: [
    {
      productId: 1,
      productName:'Candela1',
      productQuantity: 1,
      productImage:FuegoIPClipper,
      productImg2: img2,
      productImg3: img3,
      productImg4: img4,
      productTitle:'Clipper - Collection Flight1',
      productPath:`/collections/FireProducts/Candela1`,
      productPrice: 4500,
      productPriceBefore: '6.000',
      productDiscount: '25',
      productDetails:'Los encendedores Clipper son los mas conocidos gracias a sus creativos diseños y su excelente calidad, son duraderos y lo mejor es que con estos encendedores puedes recargar su gas cuando este se acabe, prolongando así la vida útil de los encendedores. También cuentan con válvulas de seguridad patentada para evitar explosiones.'
    },
    {
      productId: 2,
      productName:'Candela2',
      productQuantity: 1,
      productImage:FuegoIPClipper,
      productImg2: img2,
      productImg3: img3,
      productImg4: img4,
      productTitle:'Clipper - Collection Flight2',
      productPath:'/collections/FireProducts/Candela2',
      productPrice: 4500,
      productPriceBefore: '6.000',
      productDiscount: '25',
      productDetails:'Los encendedores Clipper son los mas conocidos gracias a sus creativos diseños y su excelente calidad, son duraderos y lo mejor es que con estos encendedores puedes recargar su gas cuando este se acabe, prolongando así la vida útil de los encendedores. También cuentan con válvulas de seguridad patentada para evitar explosiones.'
    },
    {
      productId: 3,
      productName:'MiniSopleteVerde',
      productQuantity: 1,
      productImage:MiniSopleteVerde,
      productImg2: MiniSoplete,
      productImg3: null,
      productImg4: null,
      productTitle:'Mini soplete verde Floppi',
      productPath:'/collections/FireProducts/MiniSopleteVerde',
      productPrice: 12000,
      productPriceBefore: null,
      productDiscount: null,
      productDetails:'Mini soplete encendedor marca Floppi. Potencia de la llama regulable. Sistema de seguridad antiencendido. Tamaño: 8cm x 5cm'
    },
    {
      productId: 4,
      productName:'MiniSopleteNaranja',
      productQuantity: 1,
      productImage:MiniSopleteNaranja,
      productImg2: MiniSoplete,
      productImg3: null,
      productImg4: null,
      productTitle:'Mini soplete naranja Floppi',
      productPath:'/collections/AptoProducts/MiniSopleteNaranja',
      productPrice: 12000,
      productPriceBefore: null,
      productDiscount: null,
      productDetails:'Mini soplete encendedor marca Floppi. Potencia de la llama regulable. Sistema de seguridad antiencendido. Tamaño: 8cm x 5cm'
    },
    {
      productId: 5,
      productName:'MiniSopleteNegro',
      productImage:MiniSopleteNegro,
      productQuantity: 1,
      productImg2: MiniSoplete,
      productImg3: null,
      productImg4: null,
      productTitle:'Mini soplete negro Floppi',
      productPath:'/collections/FireProducts/MiniSopleteNegro',
      productPrice: 12000,
      productPriceBefore: null,
      productDiscount: null,
      productDetails:'Mini soplete encendedor marca Floppi. Potencia de la llama regulable. Sistema de seguridad antiencendido. Tamaño: 8cm x 5cm'
    },
    {
      productId: 6,
      productImage:FuegoIPClipper,
      productQuantity: 1,
      productImg2: img2,
      productImg3: img3,
      productImg4: img4,
      productTitle:'Clipper - Collection Apto3',
      productPath:'/collections/AptoProducts/Candela3',
      productPrice: 4500,
      productPriceBefore: '6.000',
      productDiscount: '25',
      productDetails:'Los encendedores Clipper son los mas conocidos gracias a sus creativos diseños y su excelente calidad, son duraderos y lo mejor es que con estos encendedores puedes recargar su gas cuando este se acabe, prolongando así la vida útil de los encendedores. También cuentan con válvulas de seguridad patentada para evitar explosiones.'
    },
    {
      productId: 7,
      productImage:FuegoIPClipper,
      productQuantity: 1,
      productImg2: img2,
      productImg3: img3,
      productImg4: img4,
      productTitle:'Clipper - Collection Dabs1',
      productPath:'/collections/DabsProducts/Candela1',
      productPrice: 4500,
      productPriceBefore: '6.000',
      productDiscount: '25',
      productDetails:'Los encendedores Clipper son los mas conocidos gracias a sus creativos diseños y su excelente calidad, son duraderos y lo mejor es que con estos encendedores puedes recargar su gas cuando este se acabe, prolongando así la vida útil de los encendedores. También cuentan con válvulas de seguridad patentada para evitar explosiones.'
    },
    {
      productId: 8,
      productQuantity: 1,
      productImage:FuegoIPClipper,
      productImg2: img2,
      productImg3: img3,
      productImg4: img4,
      productTitle:'Clipper - Collection Dabs2',
      productPath:'/collections/DabsProducts/Candela2',
      productPrice: 4500,
      productPriceBefore: '6.000',
      productDiscount: '25',
      productDetails:'Los encendedores Clipper son los mas conocidos gracias a sus creativos diseños y su excelente calidad, son duraderos y lo mejor es que con estos encendedores puedes recargar su gas cuando este se acabe, prolongando así la vida útil de los encendedores. También cuentan con válvulas de seguridad patentada para evitar explosiones.'
    },
    {
      productId: 9,
      productImage:FuegoIPClipper,
      productImg2: img2,
      productImg3: img3,
      productImg4: img4,
      productTitle:'Clipper - Collection Dabs3',
      productPath:'/collections/DabsProducts/Candela3',
      productPrice: 4500,
      productPriceBefore: '6.000',
      productDiscount: '25',
      productDetails:'Los encendedores Clipper son los mas conocidos gracias a sus creativos diseños y su excelente calidad, son duraderos y lo mejor es que con estos encendedores puedes recargar su gas cuando este se acabe, prolongando así la vida útil de los encendedores. También cuentan con válvulas de seguridad patentada para evitar explosiones.'
    },
    {
      productId: 10,
      productImage:FuegoIPClipper,
      productImg2: img2,
      productImg3: img3,
      productImg4: img4,
      productTitle:'Clipper - Collection Electronics1',
      productPath:'/collections/ElectronicsProducts/Candela1',
      productPrice: 4500,
      productPriceBefore: '6.000',
      productDiscount: '25',
      productDetails:'Los encendedores Clipper son los mas conocidos gracias a sus creativos diseños y su excelente calidad, son duraderos y lo mejor es que con estos encendedores puedes recargar su gas cuando este se acabe, prolongando así la vida útil de los encendedores. También cuentan con válvulas de seguridad patentada para evitar explosiones.'
    },
    {
      productId: 11,
      productImage:FuegoIPClipper,
      productImg2: img2,
      productImg3: img3,
      productImg4: img4,
      productTitle:'Clipper - Collection Electronics2',
      productPath:'/collections/ElectronicsProducts/Candela2',
      productPrice: 4500,
      productPriceBefore: '6.000',
      productDiscount: '25',
      productDetails:'Los encendedores Clipper son los mas conocidos gracias a sus creativos diseños y su excelente calidad, son duraderos y lo mejor es que con estos encendedores puedes recargar su gas cuando este se acabe, prolongando así la vida útil de los encendedores. También cuentan con válvulas de seguridad patentada para evitar explosiones.'
    },
    {
      productId: 12,
      productImage:FuegoIPClipper,
      productImg2: img2,
      productImg3: img3,
      productImg4: img4,
      productTitle:'Clipper - Collection Electronics3',
      productPath:'/collections/ElectronicsProducts/Candela3',
      productPrice: 4500,
      productPriceBefore: '6.000',
      productDiscount: '25',
      productDetails:'Los encendedores Clipper son los mas conocidos gracias a sus creativos diseños y su excelente calidad, son duraderos y lo mejor es que con estos encendedores puedes recargar su gas cuando este se acabe, prolongando así la vida útil de los encendedores. También cuentan con válvulas de seguridad patentada para evitar explosiones.'
    },
    {
      productId: 13,
      productImage:FuegoIPClipper,
      productImg2: img2,
      productImg3: img3,
      productImg4: img4,
      productTitle:'Clipper - Collection Glass1',
      productPath:'/collections/GlassProducts/Candela1',
      productPrice: 4500,
      productPriceBefore: '6.000',
      productDiscount: '25',
      productDetails:'Los encendedores Clipper son los mas conocidos gracias a sus creativos diseños y su excelente calidad, son duraderos y lo mejor es que con estos encendedores puedes recargar su gas cuando este se acabe, prolongando así la vida útil de los encendedores. También cuentan con válvulas de seguridad patentada para evitar explosiones.'
    },
    {
      productId: 14,
      productImage:FuegoIPClipper,
      productImg2: img2,
      productImg3: img3,
      productImg4: img4,
      productTitle:'Clipper - Collection Glass2',
      productPath:'/collections/GlassProducts/Candela2',
      productPrice: 4500,
      productPriceBefore: '6.000',
      productDiscount: '25',
      productDetails:'Los encendedores Clipper son los mas conocidos gracias a sus creativos diseños y su excelente calidad, son duraderos y lo mejor es que con estos encendedores puedes recargar su gas cuando este se acabe, prolongando así la vida útil de los encendedores. También cuentan con válvulas de seguridad patentada para evitar explosiones.'
    },
    {
      productId: 15,
      productImage:FuegoIPClipper,
      productImg2: img2,
      productImg3: img3,
      productImg4: img4,
      productTitle:'Clipper - Collection Glass3',
      productPath:'/collections/GlassProducts/Candela3',
      productPrice: 4500,
      productPriceBefore: '6.000',
      productDiscount: '25',
      productDetails:'Los encendedores Clipper son los mas conocidos gracias a sus creativos diseños y su excelente calidad, son duraderos y lo mejor es que con estos encendedores puedes recargar su gas cuando este se acabe, prolongando así la vida útil de los encendedores. También cuentan con válvulas de seguridad patentada para evitar explosiones.'
    },
    {
      productId: 16,
      productImage:FuegoIPClipper,
      productImg2: img2,
      productImg3: img3,
      productImg4: img4,
      productTitle:'Clipper - Collection Grow1',
      productPath:'/collections/GrowProducts/Candela1',
      productPrice: 4500,
      productPriceBefore: '6.000',
      productDiscount: '25',
      productDetails:'Los encendedores Clipper son los mas conocidos gracias a sus creativos diseños y su excelente calidad, son duraderos y lo mejor es que con estos encendedores puedes recargar su gas cuando este se acabe, prolongando así la vida útil de los encendedores. También cuentan con válvulas de seguridad patentada para evitar explosiones.'
    },
    {
      productId: 17,
      productImage:FuegoIPClipper,
      productImg2: img2,
      productImg3: img3,
      productImg4: img4,
      productTitle:'Clipper - Collection Grow2',
      productPath:'/collections/GrowProducts/Candela2',
      productPrice: 4500,
      productPriceBefore: '6.000',
      productDiscount: '25',
      productDetails:'Los encendedores Clipper son los mas conocidos gracias a sus creativos diseños y su excelente calidad, son duraderos y lo mejor es que con estos encendedores puedes recargar su gas cuando este se acabe, prolongando así la vida útil de los encendedores. También cuentan con válvulas de seguridad patentada para evitar explosiones.'
    },
    {
      productId: 18,
      productImage:FuegoIPClipper,
      productImg2: img2,
      productImg3: img3,
      productImg4: img4,
      productTitle:'Clipper - Collection Grow3',
      productPath:'/collections/GrowProducts/Candela3',
      productPrice: 4500,
      productPriceBefore: '6.000',
      productDiscount: '25',
      productDetails:'Los encendedores Clipper son los mas conocidos gracias a sus creativos diseños y su excelente calidad, son duraderos y lo mejor es que con estos encendedores puedes recargar su gas cuando este se acabe, prolongando así la vida útil de los encendedores. También cuentan con válvulas de seguridad patentada para evitar explosiones.'
    },
    {
      productId: 19,
      productImage:FuegoIPClipper,
      productImg2: img2,
      productImg3: img3,
      productImg4: img4,
      productTitle:'Clipper - Collection Kits1',
      productPath:'/collections/KitsProducts/Candela1',
      productPrice: 4500,
      productPriceBefore: '6.000',
      productDiscount: '25',
      productDetails:'Los encendedores Clipper son los mas conocidos gracias a sus creativos diseños y su excelente calidad, son duraderos y lo mejor es que con estos encendedores puedes recargar su gas cuando este se acabe, prolongando así la vida útil de los encendedores. También cuentan con válvulas de seguridad patentada para evitar explosiones.'
    },
    {
      productId: 20,
      productImage:FuegoIPClipper,
      productImg2: img2,
      productImg3: img3,
      productImg4: img4,
      productTitle:'Clipper - Collection Kits2',
      productPath:'/collections/KitsProducts/Candela2',
      productPrice: 4500,
      productPriceBefore: '6.000',
      productDiscount: '25',
      productDetails:'Los encendedores Clipper son los mas conocidos gracias a sus creativos diseños y su excelente calidad, son duraderos y lo mejor es que con estos encendedores puedes recargar su gas cuando este se acabe, prolongando así la vida útil de los encendedores. También cuentan con válvulas de seguridad patentada para evitar explosiones.'
    },
    {
      productId: 21,
      productImage:FuegoIPClipper,
      productImg2: img2,
      productImg3: img3,
      productImg4: img4,
      productTitle:'Clipper - Collection Kits3',
      productPath:'/collections/KitsProducts/Candela3',
      productPrice: 4500,
      productPriceBefore: '6.000',
      productDiscount: '25',
      productDetails:'Los encendedores Clipper son los mas conocidos gracias a sus creativos diseños y su excelente calidad, son duraderos y lo mejor es que con estos encendedores puedes recargar su gas cuando este se acabe, prolongando así la vida útil de los encendedores. También cuentan con válvulas de seguridad patentada para evitar explosiones.'
    },
    {
      productId: 22,
      productImage:FuegoIPClipper,
      productImg2: img2,
      productImg3: img3,
      productImg4: img4,
      productTitle:'Clipper - Collection Medicinal1',
      productPath:'/collections/MedicinalProducts/Candela1',
      productPrice: 4500,
      productPriceBefore: '6.000',
      productDiscount: '25',
      productDetails:'Los encendedores Clipper son los mas conocidos gracias a sus creativos diseños y su excelente calidad, son duraderos y lo mejor es que con estos encendedores puedes recargar su gas cuando este se acabe, prolongando así la vida útil de los encendedores. También cuentan con válvulas de seguridad patentada para evitar explosiones.'
    },
    {
      productId: 23,
      productImage:FuegoIPClipper,
      productImg2: img2,
      productImg3: img3,
      productImg4: img4,
      productTitle:'Clipper - Collection Medicinal2',
      productPath:'/collections/MedicinalProducts/Candela2',
      productPrice: 4500,
      productPriceBefore: '6.000',
      productDiscount: '25',
      productDetails:'Los encendedores Clipper son los mas conocidos gracias a sus creativos diseños y su excelente calidad, son duraderos y lo mejor es que con estos encendedores puedes recargar su gas cuando este se acabe, prolongando así la vida útil de los encendedores. También cuentan con válvulas de seguridad patentada para evitar explosiones.'
    },
    {
      productId: 24,
      productImage:FuegoIPClipper,
      productImg2: img2,
      productImg3: img3,
      productImg4: img4,
      productTitle:'Clipper - Collection Medicinal3',
      productPath:'/collections/MedicinalProducts/Candela3',
      productPrice: 4500,
      productPriceBefore: '6.000',
      productDiscount: '25',
      productDetails:'Los encendedores Clipper son los mas conocidos gracias a sus creativos diseños y su excelente calidad, son duraderos y lo mejor es que con estos encendedores puedes recargar su gas cuando este se acabe, prolongando así la vida útil de los encendedores. También cuentan con válvulas de seguridad patentada para evitar explosiones.'
    },
    {
      productId: 25,
      productImage:FuegoIPClipper,
      productImg2: img2,
      productImg3: img3,
      productImg4: img4,
      productTitle:'Clipper - Collection Paper',
      productPath:'/collections/PaperProducts/Candela1',
      productPrice:4500,
      productPriceBefore: '6.000',
      productDiscount: '25',
      productDetails:'Los encendedores Clipper son los mas conocidos gracias a sus creativos diseños y su excelente calidad, son duraderos y lo mejor es que con estos encendedores puedes recargar su gas cuando este se acabe, prolongando así la vida útil de los encendedores. También cuentan con válvulas de seguridad patentada para evitar explosiones.'
    },
    {
      productId: 26,
      productImage:FuegoIPClipper,
      productImg2: img2,
      productImg3: img3,
      productImg4: img4,
      productTitle:'Clipper - Collection Paper2',
      productPath:'/collections/PaperProducts/Candela2',
      productPrice:4500,
      productPriceBefore: '6.000',
      productDiscount: '25',
      productDetails:'Los encendedores Clipper son los mas conocidos gracias a sus creativos diseños y su excelente calidad, son duraderos y lo mejor es que con estos encendedores puedes recargar su gas cuando este se acabe, prolongando así la vida útil de los encendedores. También cuentan con válvulas de seguridad patentada para evitar explosiones.'
    },
    {
      productId: 27,
      productImage:FuegoIPClipper,
      productImg2: img2,
      productImg3: img3,
      productImg4: img4,
      productTitle:'Clipper - Collection Paper3',
      productPath:'/collections/PaperProducts/Candela3',
      productPrice:4500,
      productPriceBefore: '6.000',
      productDiscount: '25',
      productDetails:'Los encendedores Clipper son los mas conocidos gracias a sus creativos diseños y su excelente calidad, son duraderos y lo mejor es que con estos encendedores puedes recargar su gas cuando este se acabe, prolongando así la vida útil de los encendedores. También cuentan con válvulas de seguridad patentada para evitar explosiones.'
    },
  ],

};
export default data2;